# Generated by Django 5.2.9 on 2026-01-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updated_a',
            new_name='updated_at',
        ),
    ]
